### ISSUE TITLE
已有django项目运行python manage.py gen_all命令时候出错了

### ISSUE THREAD

**Issue by liuxingera** [mtianyan/tyadmin_api_cli#1]
H:\Program Files\Python\Lib\site-packages\tyadmin_api_cli
<class 'django.db.models.fields.NOT_PROVIDED'>
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "H:\Program Files\Python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "H:\Program Files\Python\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "H:\Program Files\Python\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "H:\Program Files\Python\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "H:\Program Files\Python\lib\site-packages\tyadmin_api_cli\management\commands\gen_all.py", line 24, in handle
    gen_all(setting_value)
  File "H:\Program Files\Python\lib\site-packages\tyadmin_api_cli\init_filter_serial_url_view.py", line 18, in gen_all
    gen_antd_pages(project_name_settings)
  File "H:\Program Files\Python\lib\site-packages\tyadmin_api_cli\deal_antd_pages.py", line 65, in gen_antd_pages
    one_c = one_c.replace("$模型显示名字$", filed.verbose_name)
TypeError: replace() argument 2 must be str, not __proxy__

**Comment by mtianyan** [comment]
提供一下你的requirements信息，可能是与第三方包 注册model不兼容，已修复proxy问题，但是第三方内部的model外键生成出来的需要自己前端做出一些修改。 加群304094780

**Comment by liuxingera** [comment]
> [要求]，[模型]，[模型]，[模型]，加群304094780
这是我的所有PIP库
Package                       Version
----------------------------- -----------
aiml                          0.9.2
altgraph                      0.16.1
amqp                          1.4.9
anyjson                       0.3.3
appdirs                       1.4.4
APScheduler                   3.3.1
asgiref                       3.2.10
asn1crypto                    0.22.0
aspy.yaml                     1.2.0
astor                         0.8.0
astroid                       2.2.5
attrs                         17.1.0
Automat                       0.6.0
backports.functools-lru-cache 1.4
beautifulsoup4                4.5.3
billiard                      3.3.0.23
captcha                       0.3
celery                        3.1.25
certifi                       2018.11.29
cffi                          1.14.3
cfgv                          1.5.0
chardet                       3.0.4
click                         6.7
colorama                      0.4.1
comtypes                      1.1.4
configobj                     5.0.6
constantly                    15.1.0
coreapi                       2.3.3
coreschema                    0.0.4
cpca                          0.4.4
cryptography                  3.1.1
cssselect                     1.0.1
cycler                        0.10.0
Cython                        0.29.21
defusedxml                    0.5.0
diff-match-patch              20121119
distlib                       0.3.1
Django                        2.1
django-admin-row-actions      0.0.4
django-adminlte-admin         0.5.2
django-adminlte-ui            1.5.1
django-appconf                1.0.1
django-bootstrap3             8.2.2
django-celery                 3.2.1
django-ckeditor               6.0.0
django-cors-headers           3.5.0
django-crispy-forms           1.9.2
django-cruds-adminlte         0.0.6
django-extensions             1.7.8
django-form-utils             1.0.3
django-formtools              2.1
django-grappelli              2.9.1
django-guardian               1.4.1
django-image-cropping         1.1.0
django-import-export          0.5.1
django-js-asset               1.2.2
django-jsonfield              1.0.1
django-mail-admin             0.1.3
django-model-utils            3.0.0
django-modelcluster           3.1
django-mptt                   0.8.7
django-polymorphic            1.0.2
django-ranged-response        0.2.0
django-redis                  4.8.0
django-reversion              2.0.8
Django-Select2                5.11.1
django-simple-captcha         0.5.13
django-stdimage               3.2.0
django-suit                   0.2.25
django-taggit                 0.22.1
django-tinymce                2.6.0
django-treebeard              4.3
django-user-accounts          2.0.3
django-userena                2.0.1
django-users2                 0.2.1
djangoajax                    2.3.7
djangorestframework           3.12.1
docopt                        0.6.2
drf-yasg                      1.17.1
easy-thumbnails               2.3
echarts-python                0.1.3
et-xmlfile                    1.0.1
filelock                      3.0.10
Flask                         0.12.1
flup6                         1.1.1
funcsigs                      1.0.2
future                        0.15.2
futures                       3.0.5
gast                          0.2.2
google-pasta                  0.1.7
gunicorn                      19.7.1
h5py                          2.10.0
html2text                     2014.12.29
html5lib                      0.999999999
httplib2                      0.9.2
hyperlink                     17.3.0
identify                      1.4.0
idna                          2.5
importlib-metadata            0.8
importlib-resources           1.0.2
incremental                   16.10.1
inflection                    0.5.1
ipaddress                     1.0.18
isort                         4.3.21
itchat                        1.2.32
itsdangerous                  0.24
itypes                        1.2.0
jdcal                         1.3
jieba                         0.39
Jinja2                        2.9.6
jsonpatch                     1.16
jsonpointer                   1.10
Keras                         2.2.4
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.0
kombu                         3.0.37
lazy-object-proxy             1.4.1
lxml                          4.5.2
macholib                      1.11
Markdown                      2.6.8
markdown2                     2.3.4
MarkupSafe                    1.1.1
mccabe                        0.6.1
MouseInfo                     0.0.4
mysql-connector               2.2.9
nodeenv                       1.3.3
numpy                         1.19.2
oauth                         1.0.1
odfpy                         1.3.5
olefile                       0.44
openpyxl                      2.4.8
packaging                     16.8
pandas                        1.1.2
parse                         1.8.2
parsel                        1.2.0
pefile                        2019.4.18
pexpect                       4.2.1
Pillow                        7.2.0
pip                           20.2.3
pipenv                        2020.8.13
pipreqs                       0.4.9
pluggy                        0.9.0
pre-commit                    1.14.4
prettytable                   0.7.2
progressbar2                  3.53.1
protobuf                      3.9.0
ptyprocess                    0.5.2
py                            1.9.0
pyasn1                        0.2.3
pyasn1-modules                0.0.8
PyAutoGUI                     0.9.50
pycparser                     2.17
PyDispatcher                  2.0.5
PyGetWindow                   0.0.7
pyinstaller                   4.0
pyinstaller-hooks-contrib     2020.9
pylint                        2.3.1
PyMsgBox                      1.0.7
PyMySQL                       0.10.1
pyOpenSSL                     17.0.0
pyparsing                     2.2.0
pyperclip                     1.7.0
pypinyin                      0.18.1
pypng                         0.0.18
PyQRCode                      1.2.1
pyquery                       1.4.0
PyRect                        0.1.4
PyScreeze                     0.1.22
pytesser3                     1.0.1
pytesseract                   0.2.7
python-dateutil               2.8.1
python-docx                   0.8.6
python-utils                  2.4.0
python-whois                  0.6.8
PyTweening                    1.0.3
pytz                          2017.2
pywin32                       228
pywin32-ctypes                0.2.0
PyYAML                        3.12
queuelib                      1.4.2
redis                         2.10.5
requests                      2.21.0
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
scipy                         1.5.2
selenium                      3.4.2
service-identity              16.0.0
setuptools                    50.3.0
simplejson                    3.10.0
six                           1.10.0
sqlparse                      0.2.3
tablib                        0.12.1
termcolor                     1.1.0
toml                          0.10.0
tox                           3.7.0
translate                     3.5.0
tyadmin-api-cli               0.2.0
typed-ast                     1.4.0
tzlocal                       1.3.2
unicodecsv                    0.14.1
Unidecode                     0.4.20
uritemplate                   3.0.1
urllib3                       1.22
virtualenv                    15.1.0
virtualenv-clone              0.5.4
w3lib                         1.17.0
webencodings                  0.5.1
Werkzeug                      0.12.1
wheel                         0.35.1
Willow                        0.4
wrapt                         1.11.2
wxpy                          0.3.9.8
xlrd                          1.0.0
XlsxWriter                    0.9.6
xlutils                       2.0.0
xlwt                          1.2.0
yarg                          0.1.9
zipp                          0.3.3
zope.interface                5.1.1
