### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by tanxfengs** [mtianyan/tyadmin_api_cli#4]
老哥你好.  windows下默认的编码为gbk, 生成的页面文件中文 ,显示乱码. 我看了一下是没有加编码导致的,这个地方是可以优化一下的.

**Comment by mtianyan** [comment]
是上一个老哥说的open encoding 问题嘛，还是其他问题。

**Comment by tanxfengs** [comment]
> 是上一个老哥说的open encoding 问题嘛，还是其他问题。

确实是的, 我没看到, 哈哈,抱歉
